<a href="https://colab.research.google.com/github/malekeechaker/NLPPreProcessing/blob/main/Vectorisation_mots.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Feature Engneering**

# Bag of Words BOW

not good -> don't represent similar words

->to much resources

->out of vocabulary problem

In [ ]:
#1st methode one_hot encoding

from sklearn.preprocessing import OneHotEncoder

enc=OneHotEncoder(handle_unknown='ignore')
X=[['he','is'],['they','are'],['she','is']]
enc.fit(X)
print(enc.categories_)
print(enc.transform(X).toarray())

[array(['he', 'she', 'they'], dtype=object), array(['are', 'is'], dtype=object)]
[[1. 0. 0. 0. 1.]
 [0. 0. 1. 1. 0.]
 [0. 1. 0. 0. 1.]]


In [ ]:
#2nd methode code from scratch
import pandas as pd
data=[["Revue 1" , "Spider man est un film incroyable !"],
["Revue 2" , "Spider man est le meilleur film !"],
["Revue 3" , "Spiderman est TELLEMENT génial."]]
df=pd.DataFrame (data,columns=["revue", "text"])
df

revue                                 text
0  Revue 1  Spider man est un film incroyable !
1  Revue 2    Spider man est le meilleur film !
2  Revue 3      Spiderman est TELLEMENT génial.

In [ ]:
from keras.preprocessing.text import text_to_word_sequence

def tokenise_text(text):

  return text_to_word_sequence(text)

#convertir la phrase en miniscule
#supprimer la ponctuation
#tokanization par espace
df["text_tok"]=df["text"].apply(tokenise_text)
df

revue                                 text  \
0  Revue 1  Spider man est un film incroyable !   
1  Revue 2    Spider man est le meilleur film !   
2  Revue 3      Spiderman est TELLEMENT génial.   

                                   text_tok  
0  [spider, man, est, un, film, incroyable]  
1    [spider, man, est, le, meilleur, film]  
2       [spiderman, est, tellement, génial]

In [ ]:

def calculBOW(document):
    bow = {}
    mots = document.split()
    for mot in mots:
        if mot in bow:
            bow[mot] += 1
        else:
            bow[mot] = 1
    return bow

df["text_bow"] = df["text"].apply(calculBOW)
df

revue                                 text  \
0  Revue 1  Spider man est un film incroyable !   
1  Revue 2    Spider man est le meilleur film !   
2  Revue 3      Spiderman est TELLEMENT génial.   

                                   text_tok  \
0  [spider, man, est, un, film, incroyable]   
1    [spider, man, est, le, meilleur, film]   
2       [spiderman, est, tellement, génial]   

                                            text_bow  
0  {'Spider': 1, 'man': 1, 'est': 1, 'un': 1, 'fi...  
1  {'Spider': 1, 'man': 1, 'est': 1, 'le': 1, 'me...  
2  {'Spiderman': 1, 'est': 1, 'TELLEMENT': 1, 'gé...

In [ ]:
#3rd methode countvectorizer
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
vecteurs_bow = vectorizer.fit_transform(df["text"])

#les mots du vocabulaire
print( vectorizer.get_feature_names_out())

#les vecteurs BOW
print( vecteurs_bow.toarray())

#dir(vecrorizer)  methodes

['est' 'film' 'génial' 'incroyable' 'le' 'man' 'meilleur' 'spider'
 'spiderman' 'tellement' 'un']
[[1 1 0 1 0 1 0 1 0 0 1]
 [1 1 0 0 1 1 1 1 0 0 0]
 [1 0 1 0 0 0 0 0 1 1 0]]


In [ ]:
#from scrach and delete stop words
stop_words = ['le', 'un', 'est', 'le', 'un']

def calculBOW(document, stop_words):
    bow = {}
    mots = document.split()
    for mot in mots:
        if mot not in stop_words:
            if mot in bow:
                bow[mot] += 1
            else:
                bow[mot] = 1
    return bow
df["text_bow_nostop"] = df["text"].apply(lambda x: calculBOW(x, stop_words))
df

revue                                 text  \
0  Revue 1  Spider man est un film incroyable !   
1  Revue 2    Spider man est le meilleur film !   
2  Revue 3      Spiderman est TELLEMENT génial.   

                                   text_tok  \
0  [spider, man, est, un, film, incroyable]   
1    [spider, man, est, le, meilleur, film]   
2       [spiderman, est, tellement, génial]   

                                            text_bow  \
0  {'Spider': 1, 'man': 1, 'est': 1, 'un': 1, 'fi...   
1  {'Spider': 1, 'man': 1, 'est': 1, 'le': 1, 'me...   
2  {'Spiderman': 1, 'est': 1, 'TELLEMENT': 1, 'gé...   

                                     text_bow_nostop  
0  {'Spider': 1, 'man': 1, 'film': 1, 'incroyable...  
1  {'Spider': 1, 'man': 1, 'meilleur': 1, 'film':...  
2     {'Spiderman': 1, 'TELLEMENT': 1, 'génial.': 1}

In [ ]:
#4th methode Bag of bigrams

vectorizer_bigrams = CountVectorizer(ngram_range=(1, 2)) #creer signle and bigram ngram_range=(start,finish)
vecteurs_bigrams = vectorizer_bigrams.fit_transform(df["text_tok"].apply(' '.join))

print( vectorizer_bigrams.get_feature_names_out())

print( vecteurs_bigrams.toarray())

['est' 'est le' 'est tellement' 'est un' 'film' 'film incroyable' 'génial'
 'incroyable' 'le' 'le meilleur' 'man' 'man est' 'meilleur'
 'meilleur film' 'spider' 'spider man' 'spiderman' 'spiderman est'
 'tellement' 'tellement génial' 'un' 'un film']
[[1 0 0 1 1 1 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 1]
 [1 1 0 0 1 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0]
 [1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0]]


**other exemple**

In [ ]:
import re

#read a text from file
with open('alice.txt', 'r') as file:
    content = file.readlines()
    new_content = [cont.replace('\n'," ") for cont in content]

print(new_content)

FileNotFoundError: [Errno 2] No such file or directory: 'alice.txt'

In [ ]:
from keras.preprocessing.text import text_to_word_sequence

#tokanization
tokenized_phrases = [text_to_word_sequence(phrase) for phrase in new_content]
tokenized_phrases

In [ ]:
#5th methode TF-IDF (term frequency-inverse document frequency) = TF * IDF
#IDF = log( nbr doc/nbr doc with term )
#TF in doc = nbr term t in doc / nbr of termss in doc

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer_TDIDF = TfidfVectorizer()
vectorizer_TDIDF.fit(new_content)
transform_output = vectorizer_TDIDF.transform(new_content)

#les mots du vocabulaire
print( vectorizer_TDIDF.get_feature_names_out())

#les vecteurs TF-IDF
print( transform_output.toarray())


# **Word Embeding**

capture similarity in the vectors

lower dimensions than BOW

In [ ]:
#1st methode Word2Vec CBOW
from gensim.models import Word2Vec

#cbow (continous bag of words) use neural natwork with the context is the input and the word is the output (to determine the vector of a word which is the weights)
model_cbow = Word2Vec(tokenized_phrases, vector_size=100, window=5, min_count=2, sg=0)

print("Vecteur du mot 'alice':", model_cbow.wv['alice'])
print("3 mots les plus similaires à 'alice':", model_cbow.wv.most_similar('alice', topn=3))



In [ ]:
#2nd methode Word2Vec SkipGram
#skipgram also use neural natwork, but with the word is the input and the context is the output (to determine the vector of a word which is the weights)
model_skipgram = Word2Vec(tokenized_phrases, vector_size=100, window=5, min_count=2, sg=1)

print("Vecteur du mot 'alice':", model_skipgram.wv['alice'])
print("3 mots les plus similaires à 'alice':", model_skipgram.wv.most_similar('alice', topn=3))


In [ ]:
import numpy as np

# Define the words for which you want to calculate cosine similarity
words = ['wonderland', 'alice', 'rabbit']

# Calculate and print cosine similarity for CBOW model
print("Cosine Similarity for CBOW Model:")
for i in range(len(words)):
    for j in range(i+1, len(words)):
        similarity = model_cbow.wv.similarity(words[i], words[j])
        print(f"Similarity between '{words[i]}' and '{words[j]}': {similarity}")



In [ ]:
# Calculate and print cosine similarity for skipgram model
print("Cosine Similarity for skipgram Model:")
for i in range(len(words)):
    for j in range(i+1, len(words)):
        similarity = model_skipgram.wv.similarity(words[i], words[j])
        print(f"Similarity between '{words[i]}' and '{words[j]}': {similarity}")


In [ ]:

mot_cible = "wonderland"

# Trouver les mots les plus similaires avec CBOW
print(f"Les mots les plus similaires à {mot_cible} par CBOW :")
similaires_cbow = model_cbow.wv.most_similar(mot_cible, topn=5)
for word, similarity in similaires_cbow:
    print(f"{word}: {similarity}")

# Trouver les mots les plus similaires avec Skip-gram
print(f"Les mots les plus similaires à {mot_cible} par Skip-gram :")
similaires_skipgram = model_skipgram.wv.most_similar(mot_cible, topn=5)
for word, similarity in similaires_skipgram:
    print(f"{word}: {similarity}")

In [ ]:
pip install spacy

In [ ]:
!python -m spacy download en_core_web_lg

In [ ]:
#3rd methode Word2Vec spacy
import spacy

# word vectors you need to install large or medium english model. We will install the large one!
nlp = spacy.load("en_core_web_lg")

In [ ]:
def print_similarity(base_word, words_to_compare):
    base_token = nlp(base_word)
    doc = nlp(words_to_compare)
    for token in doc:
        print(f"{token.text} <-> {base_token.text}: ", token.similarity(base_token))

print_similarity("iphone", "apple samsung iphone dog kitten")

In [ ]:
king = nlp.vocab["king"].vector
man = nlp.vocab["man"].vector
woman = nlp.vocab["woman"].vector
queen = nlp.vocab["queen"].vector

result = king - man + woman
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity([result], [queen])

In [ ]:
#4th methode FastText
#FastText use neural network but before that it tokenize every word : (n=3,wor,ord)
#better for OOV (words out of vocabulary)

In [ ]:
#5th methode BERT (Bidirectional Encoder Representations from Transformers)
#contextualized emmbeding (for a word-> multiple vectors for every meaning/ context)(<>fixed emmbedding for a word)